const MONGO_URI = process.env["MONGO_URI"];
const PORT = process.env["PORT"];
const JWT_SECRET_TOKEN = process.env["JWT_SECRET_TOKEN"];

const CLOUDINARY_API_KEY = process.env["CLOUDINARY_API_KEY"];
const CLOUDINARY_SECRET_KEY = process.env["CLOUDINARY_SECRET_KEY"];
const CLOUDINARY_NAME = process.env["CLOUDINARY_NAME"];

const CLOUDINARY_CV_FOLDER = process.env["CLOUDINARY_CV_FOLDER"];
const CLOUDINARY_CV_RESOURCE_TYPE = process.env["CLOUDINARY_CV_RESOURCE_TYPE"];

const CLOUDINARY_BLOG_FOLDER = process.env["CLOUDINARY_BLOG_FOLDER"];
const CLOUDINARY_BLOG_RESOUCE_TYPE =
  process.env["CLOUDINARY_BLOG_RESOUCE_TYPE"];

const EMAIL_PUBLIC_KEY = process.env["EMAIL_PUBLIC_KEY"];
const EMAIL_PRIVATE_KEY = process.env["EMAIL_PRIVATE_KEY"];

const FEEDBACK_SERVICE_ID = process.env["FEEDBACK_SERVICE_ID"];
const BOOKINGS_SERVICE_ID = process.env["BOOKINGS_SERVICE_ID"];
const JOBS_SERVICE_ID = process.env["JOBS_SERVICE_ID"];

const FEEDBACK_TEMPLATE_ID = process.env["FEEDBACK_TEMPLATE_ID"];
const APPLY_TEMPLATE_ID = process.env["APPLY_TEMPLATE_ID"];
const JOBS_TEMPLATE_ID = process.env["JOBS_TEMPLATE_ID"];

const GCLOUD_PROJECT = process.env["GCLOUD_PROJECT"];
const GOOGLE_CLIENT_EMAIL = process.env["GOOGLE_CLIENT_EMAIL"];
const GOOGLE_PRIVATE_KEY = process.env["GOOGLE_PRIVATE_KEY"];
const SHEET_ID = process.env["SHEET_ID"];
const TAB_NAME = process.env["TAB_NAME"];

const LOG_MODE = process.env["LOG_MODE"];
const CREATE_ADMIN = process.env["CREATE_ADMIN"];
const ADMIN_EMAIL = process.env["ADMIN_EMAIL"];
const ADMIN_PASS = process.env["ADMIN_PASS"];

module.exports = {
  MONGO_URI,
  PORT,
  JWT_SECRET_TOKEN,
  CLOUDINARY_API_KEY,
  CLOUDINARY_NAME,
  CLOUDINARY_SECRET_KEY,
  CLOUDINARY_BLOG_FOLDER,
  CLOUDINARY_BLOG_RESOUCE_TYPE,
  CLOUDINARY_CV_FOLDER,
  CLOUDINARY_CV_RESOURCE_TYPE,
  EMAIL_PRIVATE_KEY,
  EMAIL_PUBLIC_KEY,
  FEEDBACK_SERVICE_ID,
  FEEDBACK_TEMPLATE_ID,
  BOOKINGS_SERVICE_ID,
  APPLY_TEMPLATE_ID,
  JOBS_SERVICE_ID,
  JOBS_TEMPLATE_ID,
  GCLOUD_PROJECT,
  GOOGLE_CLIENT_EMAIL,
  GOOGLE_PRIVATE_KEY,
  SHEET_ID,
  CREATE_ADMIN,
  ADMIN_EMAIL,
  ADMIN_PASS,
  TAB_NAME,
  LOG_MODE,
};
